// <auto-generated />
using System;
using GitHubIssueTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubIssueTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501050438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GitHubIssueGitHubLabel", b =>
                {
                    b.Property<string>("IssuesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("issues_id");

                    b.Property<string>("LabelsId")
                        .HasColumnType("TEXT")
                        .HasColumnName("labels_id");

                    b.HasKey("IssuesId", "LabelsId")
                        .HasName("pk_git_hub_issue_git_hub_label");

                    b.HasIndex("LabelsId")
                        .HasDatabaseName("ix_git_hub_issue_git_hub_label_labels_id");

                    b.ToTable("git_hub_issue_git_hub_label", (string)null);
                });

            modelBuilder.Entity("GitHubIssueGitHubUser", b =>
                {
                    b.Property<string>("AssigneesId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignees_id");

                    b.Property<string>("GitHubIssueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("git_hub_issue_id");

                    b.HasKey("AssigneesId", "GitHubIssueId")
                        .HasName("pk_git_hub_issue_git_hub_user");

                    b.HasIndex("GitHubIssueId")
                        .HasDatabaseName("ix_git_hub_issue_git_hub_user_git_hub_issue_id");

                    b.ToTable("git_hub_issue_git_hub_user", (string)null);
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubIssue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at")
                        .HasAnnotation("Relational:JsonPropertyName", "closedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("GitHubIssueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("git_hub_issue_id");

                    b.Property<bool>("IsPullRequest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pull_request")
                        .HasAnnotation("Relational:JsonPropertyName", "isPullRequest");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<string>("RepositoryNameWithOwner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_name_with_owner");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_issues_author_id");

                    b.HasIndex("GitHubIssueId")
                        .HasDatabaseName("ix_issues_git_hub_issue_id");

                    b.HasIndex("RepositoryNameWithOwner")
                        .HasDatabaseName("ix_issues_repository_name_with_owner");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubLabel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubRepository", b =>
                {
                    b.Property<string>("NameWithOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_with_owner")
                        .HasAnnotation("Relational:JsonPropertyName", "nameWithOwner");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("NameWithOwner")
                        .HasName("pk_repositories");

                    b.ToTable("repositories", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "repository");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_bot")
                        .HasAnnotation("Relational:JsonPropertyName", "is_bot");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login")
                        .HasAnnotation("Relational:JsonPropertyName", "login");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "assignees");
                });

            modelBuilder.Entity("GitHubIssueGitHubLabel", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubIssue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_git_hub_label_issues_issues_id");

                    b.HasOne("GitHubIssueTracker.Models.GitHubLabel", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_git_hub_label_labels_labels_id");
                });

            modelBuilder.Entity("GitHubIssueGitHubUser", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_git_hub_user_users_assignees_id");

                    b.HasOne("GitHubIssueTracker.Models.GitHubIssue", null)
                        .WithMany()
                        .HasForeignKey("GitHubIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_git_hub_issue_git_hub_user_issues_git_hub_issue_id");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubIssue", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubUser", "Author")
                        .WithMany("Issues")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_author_id");

                    b.HasOne("GitHubIssueTracker.Models.GitHubIssue", null)
                        .WithMany("Issues")
                        .HasForeignKey("GitHubIssueId")
                        .HasConstraintName("fk_issues_issues_git_hub_issue_id");

                    b.HasOne("GitHubIssueTracker.Models.GitHubRepository", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryNameWithOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_repositories_repository_name_with_owner");

                    b.Navigation("Author");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubIssue", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubRepository", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubUser", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
