// <auto-generated />
using GitHubIssueTracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitHubIssueTracker.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430050854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GitHubIssueGitHubLabel", b =>
                {
                    b.Property<string>("LabeledIssuesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelsId")
                        .HasColumnType("TEXT");

                    b.HasKey("LabeledIssuesId", "LabelsId");

                    b.HasIndex("LabelsId");

                    b.ToTable("GitHubIssueGitHubLabel");
                });

            modelBuilder.Entity("GitHubIssueGitHubUser", b =>
                {
                    b.Property<string>("AssignedIssuesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneesId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignedIssuesId", "AssigneesId");

                    b.HasIndex("AssigneesId");

                    b.ToTable("GitHubIssueGitHubUser");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubIssue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "closedAt");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsPullRequest")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "isPullRequest");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<string>("RepositoryNameWithOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepositoryNameWithOwner");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubLabel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Labels");

                    b.HasAnnotation("Relational:JsonPropertyName", "labels");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubRepository", b =>
                {
                    b.Property<string>("NameWithOwner")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nameWithOwner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("NameWithOwner");

                    b.ToTable("Repositories");

                    b.HasAnnotation("Relational:JsonPropertyName", "repository");
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_bot");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "login");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasAnnotation("Relational:JsonPropertyName", "author");
                });

            modelBuilder.Entity("GitHubIssueGitHubLabel", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubIssue", null)
                        .WithMany()
                        .HasForeignKey("LabeledIssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitHubIssueTracker.Models.GitHubLabel", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GitHubIssueGitHubUser", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubIssue", null)
                        .WithMany()
                        .HasForeignKey("AssignedIssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitHubIssueTracker.Models.GitHubUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GitHubIssueTracker.Models.GitHubIssue", b =>
                {
                    b.HasOne("GitHubIssueTracker.Models.GitHubUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitHubIssueTracker.Models.GitHubRepository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryNameWithOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Repository");
                });
#pragma warning restore 612, 618
        }
    }
}
